services:
  minecraft:
    image: itzg/minecraft-server:java21
    container_name: minecraft-paper
    ports:
      - '25565:25565'
    environment:
      EULA: 'TRUE'
      TYPE: 'PAPER'
      VERSION: '1.21.6'
      MEMORY: '2G'
      TZ: 'UTC'
      ONLINE_MODE: 'FALSE'
      VIEW_DISTANCE: '6'
      SIMULATION_DISTANCE: '6'
      SPAWN_PROTECTION: '0'
      CONNECTION_THROTTLE: '-1'
      RESOURCE_PACK: 'https://raw.githubusercontent.com/zero-point-module/silk-monad/main/minecraft/resource-pack/pack.zip'
      RESOURCE_PACK_SHA1: '487a5434aaa11f2b3c36e1dbae95a532e2870af5'
      RESOURCE_PACK_ENFORCE: 'TRUE'
      RESOURCE_PACK_PROMPT: 'silk-monad cosmetics pack'
      MODRINTH_PROJECTS: 'viaversion,viabackwards,viarewind,skinsrestorer,fastasyncworldedit,fancynpcs'
      MODRINTH_DOWNLOAD_DEPENDENCIES: 'required'
      ENABLE_RCON: 'TRUE'
      RCON_CMDS_STARTUP: |-
        gamerule doDaylightCycle false
        gamerule doWeatherCycle false
        gamerule doFireTick false
        gamerule randomTickSpeed 0
        gamerule mobGriefing false
        time set noon
        weather clear 1000000
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./data:/data
